Traceback (most recent call last):
  File "/home/una/domain_gen/name_gen.py", line 421, in <module>
    avg_backlog = ppo_agent.train()
  File "/home/una/domain_gen/name_gen.py", line 256, in train
    next_obs, reward, terminations, truncations, infos = self.env.step(action.cpu().numpy())
  File "/home/una/domain_gen/name_gen.py", line 143, in step
    r=self.reward_function(prev)
  File "/home/una/domain_gen/name_gen.py", line 129, in reward_function
    pron=pronounceability_sld(name)
  File "/home/una/domain_gen/name_gen.py", line 39, in pronounceability_sld
    phoneme_seq = g2p(sld.lower())
  File "/home/una/.local/lib/python3.10/site-packages/g2p_en/g2p.py", line 162, in __call__
    tokens = pos_tag(words)  # tuples of (word, tag)
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/__init__.py", line 168, in pos_tag
    tagger = _get_tagger(lang)
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/__init__.py", line 110, in _get_tagger
    tagger = PerceptronTagger()
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/perceptron.py", line 183, in __init__
    self.load_from_json(lang)
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/perceptron.py", line 274, in load_from_json
    with open(loc + TAGGER_JSONS[lang]["weights"]) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/home/una/nltk_data/taggers/averaged_perceptron_tagger_eng/averaged_perceptron_tagger_eng.weights.json'
Traceback (most recent call last):
  File "/home/una/domain_gen/name_gen.py", line 421, in <module>
    avg_backlog = ppo_agent.train()
  File "/home/una/domain_gen/name_gen.py", line 256, in train
    next_obs, reward, terminations, truncations, infos = self.env.step(action.cpu().numpy())
  File "/home/una/domain_gen/name_gen.py", line 143, in step
    r=self.reward_function(prev)
  File "/home/una/domain_gen/name_gen.py", line 129, in reward_function
    pron=pronounceability_sld(name)
  File "/home/una/domain_gen/name_gen.py", line 39, in pronounceability_sld
    phoneme_seq = g2p(sld.lower())
  File "/home/una/.local/lib/python3.10/site-packages/g2p_en/g2p.py", line 162, in __call__
    tokens = pos_tag(words)  # tuples of (word, tag)
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/__init__.py", line 168, in pos_tag
    tagger = _get_tagger(lang)
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/__init__.py", line 110, in _get_tagger
    tagger = PerceptronTagger()
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/perceptron.py", line 183, in __init__
    self.load_from_json(lang)
  File "/home/una/.local/lib/python3.10/site-packages/nltk/tag/perceptron.py", line 274, in load_from_json
    with open(loc + TAGGER_JSONS[lang]["weights"]) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/home/una/nltk_data/taggers/averaged_perceptron_tagger_eng/averaged_perceptron_tagger_eng.weights.json'
